#ifndef QBRT_RESOURCETYPE_H
#define QBRT_RESOURCETYPE_H

#define RESOURCE_STRING		0x01
#define RESOURCE_MODSYM		0x02
#define RESOURCE_HASHTAG	0x03
#define RESOURCE_FUNCTION	0x80
#define RESOURCE_TYPE		0x81
#define RESOURCE_PROTOCOL	0x82
#define RESOURCE_POLYMORPH	0x83

// Function Context Enums
#define PFC_NULL	0b000
#define PFC_NONE	0b001
#define PFC_ABSTRACT	0b010
#define PFC_DEFAULT	0b011
#define PFC_OVERRIDE	0b111

#endif
